services:
  starter-db:
    image: postgres:11.12
    container_name: starter-db
    env_file:
      - ./server/.env.database
    ports:
      - "5432:5432"
    networks:
      - starter-net
    volumes:
      - ./server/dbdata:/var/lib/postgresql/data
    mem_limit: 256m
    cpus: "0.25"

  starter-web:
    build: ./web
    container_name: starter-web
    env_file:
      - ./web/.env.local
    expose:
      - "3000"
    ports:
      - "3000:3000"
    networks:
      - starter-net
    depends_on:
      - starter-server
    volumes:
      - ./web:/app
    entrypoint: ["yarn", "dev"]

  starter-server:
    build: ./server
    container_name: starter-server
    env_file:
      - ./server/.env.development
    expose:
      - "4000"
    ports:
      - "4100:4000"
    networks:
      - starter-net
    depends_on:
      - starter-db
    volumes:
      - ./server:/app
    command: /bin/sh "./entrypoint.sh"
    mem_limit: 256m
    cpus: "0.25"

networks:
  starter-net:
